### ISSUE TITLE
Error on Windows Server build during chocolatey installation

### ISSUE THREAD

**Issue by Kennochas** [vmware/packer-examples-for-vsphere#585]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

7

### HashiCorp Packer

1.8.2

### HashiCorp Packer Plugin for VMware vSphere

1.0.6

### Guest Operating System

Windows Server

### Description

It seems like something happened upstream with chocolatey, where .NET Framework 4.8 is required now, and breaks the current method the install uses

Chocolatey installs it in chocolateysetup.psm1 via the function Install-DotNet48IfMissing, then returns that a reboot is required.

### Expected Behavior

Image built

### Actual Behavior

==> vsphere-iso.windows-server-standard-core: Provisioning with powershell script: /tmp/powershell-provisioner1242506124
    vsphere-iso.windows-server-standard-core: Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
    vsphere-iso.windows-server-standard-core: Getting latest version of the Chocolatey package for download.
    vsphere-iso.windows-server-standard-core: Not using proxy.
    vsphere-iso.windows-server-standard-core: Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.0.0.
    vsphere-iso.windows-server-standard-core: Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.0.0 to C:\Users\admin~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
    vsphere-iso.windows-server-standard-core: Not using proxy.
    vsphere-iso.windows-server-standard-core: Extracting C:\Users\admin~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\admin~1\AppData\Local\Temp\chocolatey\chocoInstall
    vsphere-iso.windows-server-standard-core: Installing Chocolatey on the local machine
    vsphere-iso.windows-server-standard-core: The registry key for .Net 4.8 was not found or this is forced
    vsphere-iso.windows-server-standard-core: Downloading 'https://download.visualstudio.microsoft.com/download/pr/2d6bb6b2-226a-4baa-bdec-798822606ff1/8494001c276a4b96804cde7829c04d7f/ndp48-x86-x64-allos-enu.exe' to 'C:\Users\admin~1\AppData\Local\Temp\ndp48-x86-x64-allos-enu.exe' - the installer is 100+ MBs, so this could take a while on a slow connection.
    vsphere-iso.windows-server-standard-core: Installing 'C:\Users\admin~1\AppData\Local\Temp\ndp48-x86-x64-allos-enu.exe' - this may take awhile with no output.
    vsphere-iso.windows-server-standard-core: .NET Framework 4.8 was installed, but a reboot is required.
    vsphere-iso.windows-server-standard-core:  Please reboot the system and try to install/upgrade Chocolatey again.
    vsphere-iso.windows-server-standard-core: At C:\Users\<sensitive>\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateysetup.psm1:815 char:11
    vsphere-iso.windows-server-standard-core: +           throw ".NET Framework 4.8 was installed, but a reboot is re ...
    vsphere-iso.windows-server-standard-core: +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vsphere-iso.windows-server-standard-core:     + CategoryInfo          : OperationStopped: (.NET Framework ...ocolatey again.:String) [], RuntimeException
    vsphere-iso.windows-server-standard-core:     + FullyQualifiedErrorId : .NET Framework 4.8 was installed, but a reboot is required.
    vsphere-iso.windows-server-standard-core:  Please reboot the system and try to install/upgrade Chocolatey again.
    vsphere-iso.windows-server-standard-core:
==> vsphere-iso.windows-server-standard-core: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vsphere-iso.windows-server-standard-core: Power off VM...
==> vsphere-iso.windows-server-standard-core: Destroying VM...
==> vsphere-iso.windows-server-standard-core: Deleting cd_files image from remote datastore ...
Build 'vsphere-iso.windows-server-standard-core' errored after 12 minutes 57 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

### Steps to Reproduce

Try to build server 2019 or if you still have 2016, it fails too.

### Log Fragments and Files

```
==> vsphere-iso.windows-server-standard-core: Provisioning with powershell script: /tmp/powershell-provisioner1242506124
    vsphere-iso.windows-server-standard-core: Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
    vsphere-iso.windows-server-standard-core: Getting latest version of the Chocolatey package for download.
    vsphere-iso.windows-server-standard-core: Not using proxy.
    vsphere-iso.windows-server-standard-core: Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.0.0.
    vsphere-iso.windows-server-standard-core: Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.0.0 to C:\Users\admin~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
    vsphere-iso.windows-server-standard-core: Not using proxy.
    vsphere-iso.windows-server-standard-core: Extracting C:\Users\admin~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\admin~1\AppData\Local\Temp\chocolatey\chocoInstall
    vsphere-iso.windows-server-standard-core: Installing Chocolatey on the local machine
    vsphere-iso.windows-server-standard-core: The registry key for .Net 4.8 was not found or this is forced
    vsphere-iso.windows-server-standard-core: Downloading 'https://download.visualstudio.microsoft.com/download/pr/2d6bb6b2-226a-4baa-bdec-798822606ff1/8494001c276a4b96804cde7829c04d7f/ndp48-x86-x64-allos-enu.exe' to 'C:\Users\admin~1\AppData\Local\Temp\ndp48-x86-x64-allos-enu.exe' - the installer is 100+ MBs, so this could take a while on a slow connection.
    vsphere-iso.windows-server-standard-core: Installing 'C:\Users\admin~1\AppData\Local\Temp\ndp48-x86-x64-allos-enu.exe' - this may take awhile with no output.
    vsphere-iso.windows-server-standard-core: .NET Framework 4.8 was installed, but a reboot is required.
    vsphere-iso.windows-server-standard-core:  Please reboot the system and try to install/upgrade Chocolatey again.
    vsphere-iso.windows-server-standard-core: At C:\Users\<sensitive>\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateysetup.psm1:815 char:11
    vsphere-iso.windows-server-standard-core: +           throw ".NET Framework 4.8 was installed, but a reboot is re ...
    vsphere-iso.windows-server-standard-core: +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vsphere-iso.windows-server-standard-core:     + CategoryInfo          : OperationStopped: (.NET Framework ...ocolatey again.:String) [], RuntimeException
    vsphere-iso.windows-server-standard-core:     + FullyQualifiedErrorId : .NET Framework 4.8 was installed, but a reboot is required.
    vsphere-iso.windows-server-standard-core:  Please reboot the system and try to install/upgrade Chocolatey again.
    vsphere-iso.windows-server-standard-core:
==> vsphere-iso.windows-server-standard-core: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vsphere-iso.windows-server-standard-core: Power off VM...
==> vsphere-iso.windows-server-standard-core: Destroying VM...
==> vsphere-iso.windows-server-standard-core: Deleting cd_files image from remote datastore ...
Build 'vsphere-iso.windows-server-standard-core' errored after 12 minutes 57 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

```

**Comment by tenthirtyam** [comment]
I looks like chocolatey changed the install source...

From: https://chocolatey.org/install.ps1

To: https://community.chocolatey.org/install.ps1

Mind testing that?

**Comment by tenthirtyam** [comment]
Please note that the`main` branch has higher requirements than those provided.

**Comment by Kennochas** [comment]
Both of those URL's work, and actually go to the same file.

**Comment by Kennochas** [comment]
You can see it more, if you open https://community.chocolatey.org/api/v2/package/chocolatey and dig into the package for the chocolateysetup.psm1 file.

https://docs.chocolatey.org/en-us/choco/release-notes

under breaking changes: Upgrade to target version 4.8 of the .NET Framework - see [#2738](https://github.com/chocolatey/choco/issues/2738).

**Comment by tenthirtyam** [comment]
Thanks for the issue. I'll take a look but may remove chocolatey from `main` for the next release. 

One option might be to test flipping the following so that updates occur first - not sure if that will resolve the issue however.

```hcl
  provisioner "windows-update" {
    pause_before    = "30s"
    search_criteria = "IsInstalled=0"
    filters = [
      "exclude:$_.Title -like '*VMware*'",
      "exclude:$_.Title -like '*Preview*'",
      "exclude:$_.Title -like '*Defender*'",
      "exclude:$_.InstallationBehavior.CanRequestUserInput",
      "include:$true"
    ]
    restart_timeout = "120m"
  }

  provisioner "powershell" {
    elevated_user     = var.build_username
    elevated_password = var.build_password
    inline            = var.inline
  }
```
