### ISSUE TITLE
`develop`: Debian 12 preseed/kickstart is failing its LVM partitioning

### ISSUE THREAD

**Issue by necarnot** [vmware/packer-examples-for-vsphere#672]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

7.0.3d

### HashiCorp Packer

1.9.1

### HashiCorp Packer Plugin for VMware vSphere

1.2.0

### Guest Operating System

Ubuntu 22.04

### Description

Hi,

Using the provided debian/12/data/ks.pkrtpl.hcl leeds to a failure in disk partitioning, not preventing the actual installation, as defaults values and behaviour are used, but the actual template generated is not compliant with the partman-auto/expert_recipe partitions defined.

I'm still trying to debug it, but it may look like the device (the disk) is not found at the moment this preseed module is used.

### Expected Behavior

The defined partitioning is respected.

### Actual Behavior

The default partitioning is used.

### Steps to Reproduce

Just use the default preseed file (debian/12/data/ks.pkrtpl.hcl).

**Comment by tenthirtyam** [comment]
Latest is `main` and does not include Debian 12. I assume you mean the `develop` branch?

**Comment by tenthirtyam** [comment]
Do you see the same issue with Debian 11?

**Comment by necarnot** [comment]
> Do you see the same issue with Debian 11?

Hi @tenthirtyam ,

Yes, after using the resulting template to create a new VM, here is how the LVM setup looks like : 

```
root@localhost:~# pvs
  PV         VG    Fmt  Attr PSize   PFree 
  /dev/sda3  sysvg lvm2 a--  <19,02g 24,00m
root@localhost:~# vgs
  VG    #PV #LV #SN Attr   VSize   VFree 
  sysvg   1   2   0 wz--n- <19,02g 24,00m
root@localhost:~# lvs
  LV     VG    Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root   sysvg -wi-ao----  18,04g                                                    
  swap_1 sysvg -wi-ao---- 976,00m     

root@localhost:~# lsblk -f
NAME             FSTYPE      FSVER    LABEL UUID                                   FSAVAIL FSUSE% MOUNTPOINT
sda                                                                                               
├─sda1           vfat        FAT32          803A-E0E9                               505,2M     1% /boot/efi
├─sda2           ext2        1.0            ab2e1bec-da4b-4c41-bab9-3d161621e0bc    358,8M    19% /boot
└─sda3           LVM2_member LVM2 001       ws3Kmh-9QrM-XXNb-pQz1-KcwQ-MS9D-kHe4No                
  ├─sysvg-root   ext4        1.0            c6ad91bf-b526-42dd-90b6-342036e73682     15,2G     8% /
  └─sysvg-swap_1 swap        1              19fb48d1-ba32-40d7-941e-151bb9b00051                  [SWAP]
```


So it looks like the lvm naming has been taken into account ("sysvg"), but not the precise detailed partitions setup.

TBH, I'm having trouble debugging this, because though I can attach a vsphere console, enter a shell and read the log files, I find no way to stop the execution of debian-installer, so at some point, the whole process naturally leads to the VM reboot...

**Comment by necarnot** [comment]
@tenthirtyam I was able to enter the console and find that error message I was looking for : it seems I have reduced the total disk size too much for my needs, leading to the following message : 

partman-auto: Available disk space (21474) too small for expert recipe (25600); skipping

Though it looks absolutely crystal clear that this is the cause, I also was expecting that, amongst my other tries in which I specified flexible partitions sizes, partman would be able to auto adjust.

Might I ask you not to close this issue now and let me add some more tries for deb 11 and 12, and I'll write down my results here, confirming all this.

**Comment by necarnot** [comment]
@tenthirtyam OK we can close this issue, and I'm so sorry to have bothered you for that.

Just for the record, and for whoever next one who will want to enter a console during the preseed setup : I managed to gain some time before the VM is rebooted by adding a very looooong sleep at the end of the : 

d-i preseed/late_command string

command, in the builds/linux/debian/12/data/ks.pkrtpl.hcl file.
Entering the vsphere console with a alt-left_arrow combination, then reading at the /var/log files was helpful.
