### ISSUE TITLE
Ansible gather problem with Fedora 40

### ISSUE THREAD

**Issue by JM2K69** [vmware/packer-examples-for-vsphere#903]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.3

### HashiCorp Packer Plugin for VMware vSphere

1.2.7

### Guest Operating System

Fedora Sever 40

### Description

Ansible seems detect my Fedora like an Debian OS family

### Expected Behavior

It need to launch dnf upgrade or yum upgrade but not.

### Actual Behavior

It seems to launch apt-update

### Steps to Reproduce

I Clone the repos , donwload the iso with the script download.sh and go.

### Screenshots

![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/17923944/ace4ac7c-e36e-4915-a77f-d21cd5bbb2cf)

**Comment by JM2K69** [comment]
I test with Almalinux 9.3 same problem.

**Comment by tenthirtyam** [comment]
Ah, must have a collision based on the changes that were in flight for cloudinit support. I'll take care of it.  Thanks for reporting this!

**Comment by tenthirtyam** [comment]
Yep, it's literally an accidental bump in spacing in the YAML.

**Comment by tenthirtyam** [comment]
Move L53 back two spaces and test if you could. That should fix it. Free free to PR it if you like.

**Comment by JM2K69** [comment]
I'll test and make a PR afterwards
