### ISSUE TITLE
Windows Server 2025 wrong variables

### ISSUE THREAD

**Issue by JM2K69** [vmware/packer-examples-for-vsphere#906]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.3

### HashiCorp Packer Plugin for VMware vSphere

1.26.7

### Guest Operating System

Windows Server 2025

### Description

In file **windows-server-2025.pkvars.hcl** wrong variables use for keys

Use :
* **vm_inst_kms_key_standard**
* **vm_inst_kms_key_datacenter**

but need to use 
* **vm_inst_os_key_standard**
* **vm_inst_os_key_datacenter**

### Expected Behavior

impossible to startup the build

### Actual Behavior

built must started

### Steps to Reproduce

Launch a build

### Screenshots

![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/17923944/d2493519-e916-4d6f-8dbd-5db9ba93403e)

**Comment by JM2K69** [comment]
I will sent a PR

**Comment by JM2K69** [comment]
This issue has been resolved

**Comment by tenthirtyam** [comment]
Set the correct default for eval in #907.
